# Prometheus configuration for eBIOS monitoring

global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'ebios-production'
    environment: 'production'

# Alerting configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets: []
          # - alertmanager:9093

# Scrape configurations
scrape_configs:
  # eBIOS API metrics
  - job_name: 'ebios-api'
    static_configs:
      - targets: ['ebios:8080']
    metrics_path: '/metrics'
    scrape_interval: 10s

  # PostgreSQL exporter (if using postgres_exporter)
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres-exporter:9187']
    scrape_interval: 30s

  # Node exporter for system metrics (optional)
  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 15s

# Recording rules
rule_files:
  # - "alerts.yml"
